### ISSUE TITLE
Misspelled word in homepage.

### ISSUE THREAD

**Issue by NPDebs** [research-fosdem/research-fosdem.github.io#22]
Hello. 👋
A tiny typographical error was spotted on your [homepage](https://research-fosdem.github.io/), as seen in the screenshot provided below:

![IMG_20231208_210904](https://github.com/research-fosdem/research-fosdem.github.io/assets/105166953/fb9cd2a8-a595-4b48-8259-af7bfb94dd59)

I'll PR a quick fix for that and you can review at your convenience. Thanks!

**Comment by yochannah** [comment]
fixed by #23
