### ISSUE TITLE
Research Code of Conduct for repository & participants

### ISSUE THREAD

**Issue by aleesteele** [research-fosdem/research-fosdem.github.io#25]
During our meeting today (22/1) we were talking about the parallel online session that we will be organising the week after FOSDEM 2024, which will be happening in person in Brussels this year. To establish norms & ways of working for the digital presentations, we discussed the need for having a FOSDEM Open Research 'Code of Conduct' to share with folks to start their sessions.

Do we also need a set of guidelines for people who want to make their slides for accessible and/or readable online, maybe some 'Presentation Guidelines' or best practices?

**Comment by yochannah** [comment]
@aleesteele  - would you be comfy making a PR for a CoC forked from a friendly org?

**Comment by aleesteele** [comment]
@yochannah - for sure! I had it on my to do list today to respond to the email thread directly, and make a pr. thanks for the reminder 😄

**Comment by aleesteele** [comment]
Just finishing up this PR, but realised I can't submit a PR directly without forking! @jacomyma - any chance I could get write access to the repository? 😄

**Comment by jacomyma** [comment]
Oops, I only see this now... But you've been added from what I see. Else just ping me again!

**Comment by yochannah** [comment]
this has been merged, closing the issue :)
